import type { Category, Product, Promotion } from "@/lib/types";

const now = "2026-08-01T08:00:00.000Z";

export const seedCategories: Category[] = [
  {
    id: "cat-perfumes",
    name: "Perfumes",
    slug: "perfumes",
    description: "Elegant fragrances for every mood, moment and signature style.",
    imageUrl: null,
    sortOrder: 1,
    active: true,
  },
  {
    id: "cat-earrings",
    name: "Earrings",
    slug: "earrings",
    description: "Polished hoops and statement pairs that finish every look.",
    imageUrl: null,
    sortOrder: 2,
    active: true,
  },
  {
    id: "cat-necklaces",
    name: "Necklaces",
    slug: "necklaces",
    description: "Delicate and expressive necklaces made for effortless layering.",
    imageUrl: null,
    sortOrder: 3,
    active: true,
  },
  {
    id: "cat-bracelets",
    name: "Bracelets",
    slug: "bracelets",
    description: "Charming finishing touches with a graceful everyday glow.",
    imageUrl: null,
    sortOrder: 4,
    active: true,
  },
  {
    id: "cat-rings",
    name: "Rings",
    slug: "rings",
    description: "Simple statement rings designed for mixing and matching.",
    imageUrl: null,
    sortOrder: 5,
    active: true,
  },
  {
    id: "cat-gift-sets",
    name: "Gift Sets",
    slug: "gift-sets",
    description: "Thoughtful fragrance and jewellery pairings for beautiful occasions.",
    imageUrl: null,
    sortOrder: 6,
    active: true,
  },
];

function product(
  input: Omit<Product, "category" | "images" | "options" | "variants" | "createdAt" | "updatedAt"> & {
    option?: { name: string; values: string[] };
    variants?: Array<{ label: string; value: string; priceCents?: number; stockStatus?: Product["stockStatus"] }>;
  },
): Product {
  const { option, variants, ...productFields } = input;
  const category = seedCategories.find((item) => item.id === productFields.categoryId)!;
  const optionId = option ? `option-${productFields.id}` : null;
  return {
    ...productFields,
    category,
    images: [],
    options: option
      ? [{ id: optionId!, productId: productFields.id, name: option.name, values: option.values, sortOrder: 1 }]
      : [],
    variants: (variants || []).map((variant, index) => ({
      id: `variant-${productFields.id}-${index + 1}`,
      productId: productFields.id,
      label: variant.label,
      optionValues: option ? { [option.name]: variant.value } : {},
      sku: null,
      priceCents: variant.priceCents ?? null,
      stockStatus: variant.stockStatus ?? productFields.stockStatus,
      active: true,
    })),
    createdAt: now,
    updatedAt: now,
  };
}

export const seedProducts: Product[] = [
  product({
    id: "signature-bloom",
    slug: "womens-signature-perfume",
    name: "Women’s Signature Perfume",
    categoryId: "cat-perfumes",
    description: "A polished, feminine fragrance for confident everyday wear.",
    longDescription: "An easy signature scent chosen for graceful everyday wear, with a refined finish that moves beautifully from daytime plans to evening moments.",
    priceCents: 1800,
    oldPriceCents: null,
    badge: "Popular",
    featured: true,
    isNew: false,
    publicationStatus: "published",
    stockStatus: "in_stock",
    sortOrder: 1,
    option: { name: "Size", values: ["30 ml", "50 ml"] },
    variants: [
      { label: "30 ml", value: "30 ml" },
      { label: "50 ml", value: "50 ml", priceCents: 2400, stockStatus: "low_stock" },
    ],
  }),
  product({
    id: "vanilla-cloud",
    slug: "sweet-vanilla-fragrance",
    name: "Sweet Vanilla Fragrance",
    categoryId: "cat-perfumes",
    description: "Warm, creamy and sweet—an easy scent for day or night.",
    longDescription: "A cosy vanilla-led fragrance with a smooth, inviting character. It is warm without feeling heavy and beautifully suited to relaxed days and soft evening looks.",
    priceCents: 1500,
    oldPriceCents: 1800,
    badge: "Sale",
    featured: true,
    isNew: false,
    publicationStatus: "published",
    stockStatus: "low_stock",
    sortOrder: 2,
  }),
  product({
    id: "floral-muse",
    slug: "floral-muse-perfume",
    name: "Floral Muse Perfume",
    categoryId: "cat-perfumes",
    description: "A light floral scent with a soft, modern finish.",
    longDescription: "Fresh floral notes meet a clean modern finish in this bright, feminine fragrance selected for effortless daily confidence.",
    priceCents: 1700,
    oldPriceCents: null,
    badge: "New",
    featured: true,
    isNew: true,
    publicationStatus: "published",
    stockStatus: "in_stock",
    sortOrder: 3,
  }),
  product({
    id: "midnight-luxe",
    slug: "luxury-inspired-fragrance",
    name: "Luxury Inspired Fragrance",
    categoryId: "cat-perfumes",
    description: "A deeper, sophisticated scent for evenings and occasions.",
    longDescription: "A confident, evening-ready fragrance with a richer profile and a polished dry-down—ideal when the moment calls for something memorable.",
    priceCents: 2200,
    oldPriceCents: null,
    badge: "Popular",
    featured: true,
    isNew: false,
    publicationStatus: "published",
    stockStatus: "in_stock",
    sortOrder: 4,
  }),
  product({
    id: "gold-drop-earrings",
    slug: "gold-tone-drop-earrings",
    name: "Gold-Tone Drop Earrings",
    categoryId: "cat-earrings",
    description: "Elegant statement earrings with an easy golden glow.",
    longDescription: "A graceful drop silhouette with a warm gold-tone finish, selected to add a polished statement without overwhelming your look.",
    priceCents: 800,
    oldPriceCents: null,
    badge: "New",
    featured: true,
    isNew: true,
    publicationStatus: "published",
    stockStatus: "in_stock",
    sortOrder: 5,
  }),
  product({
    id: "classic-hoops",
    slug: "classic-hoop-earrings",
    name: "Classic Hoop Earrings",
    categoryId: "cat-earrings",
    description: "A versatile everyday pair that works with every look.",
    longDescription: "Clean, flattering hoops made for repeat wear. Choose the finish that suits your jewellery mood and let them carry you from casual to dressed up.",
    priceCents: 600,
    oldPriceCents: 800,
    badge: "Sale",
    featured: true,
    isNew: false,
    publicationStatus: "published",
    stockStatus: "in_stock",
    sortOrder: 6,
    option: { name: "Finish", values: ["Gold tone", "Silver tone"] },
    variants: [
      { label: "Gold tone", value: "Gold tone" },
      { label: "Silver tone", value: "Silver tone", stockStatus: "low_stock" },
    ],
  }),
  product({
    id: "delicate-necklace",
    slug: "elegant-layering-necklace",
    name: "Elegant Layering Necklace",
    categoryId: "cat-necklaces",
    description: "A delicate piece designed to shine alone or layered.",
    longDescription: "A refined necklace with a delicate profile that feels complete on its own and pairs beautifully with your existing favourites.",
    priceCents: 1200,
    oldPriceCents: null,
    badge: "Popular",
    featured: true,
    isNew: false,
    publicationStatus: "published",
    stockStatus: "in_stock",
    sortOrder: 7,
  }),
  product({
    id: "charm-bracelet",
    slug: "everyday-charm-bracelet",
    name: "Everyday Charm Bracelet",
    categoryId: "cat-bracelets",
    description: "A playful polished bracelet for a touch of personality.",
    longDescription: "A light, charming bracelet selected to bring personality and movement to everyday outfits while staying easy to style.",
    priceCents: 1000,
    oldPriceCents: null,
    badge: "New",
    featured: true,
    isNew: true,
    publicationStatus: "published",
    stockStatus: "low_stock",
    sortOrder: 8,
  }),
  product({
    id: "stacking-ring",
    slug: "minimal-fashion-ring",
    name: "Minimal Fashion Ring",
    categoryId: "cat-rings",
    description: "A simple statement ring made for mixing and matching.",
    longDescription: "A sleek fashion ring with a clean silhouette. Wear it alone for a subtle finish or combine it with your favourite pieces.",
    priceCents: 700,
    oldPriceCents: null,
    badge: "New",
    featured: false,
    isNew: true,
    publicationStatus: "published",
    stockStatus: "in_stock",
    sortOrder: 9,
    option: { name: "Size", values: ["6", "7", "8"] },
    variants: [
      { label: "Size 6", value: "6" },
      { label: "Size 7", value: "7", stockStatus: "low_stock" },
      { label: "Size 8", value: "8", stockStatus: "out_of_stock" },
    ],
  }),
  product({
    id: "luxe-gift-set",
    slug: "jewellery-perfume-gift-set",
    name: "Jewellery & Perfume Gift Set",
    categoryId: "cat-gift-sets",
    description: "A ready-to-delight pairing for celebrations and surprises.",
    longDescription: "A thoughtful Ottie Luxe pairing presented for gifting. Confirm the current fragrance and jewellery choices with us on WhatsApp before ordering.",
    priceCents: 2800,
    oldPriceCents: 3300,
    badge: "Popular",
    featured: true,
    isNew: false,
    publicationStatus: "published",
    stockStatus: "in_stock",
    sortOrder: 10,
  }),
];

export const seedPromotions: Promotion[] = [
  {
    id: "promo-duo",
    slug: "ottie-duo",
    title: "The Ottie Duo",
    subtitle: "Perfume + Earrings",
    description: "Pair a signature scent with an elegant finishing touch.",
    priceLabel: "Ask for the current duo price",
    imageUrl: null,
    productIds: ["signature-bloom", "gold-drop-earrings"],
    startsAt: null,
    endsAt: null,
    publicationStatus: "published",
    sortOrder: 1,
  },
  {
    id: "promo-birthday",
    slug: "birthday-luxe-box",
    title: "Birthday Luxe Box",
    subtitle: "Perfume + Jewellery + Gift Packaging",
    description: "A celebration-ready combination made to feel extra special.",
    priceLabel: "Customise your box on WhatsApp",
    imageUrl: null,
    productIds: ["luxe-gift-set"],
    startsAt: null,
    endsAt: null,
    publicationStatus: "published",
    sortOrder: 2,
  },
  {
    id: "promo-bestie",
    slug: "bestie-bundle",
    title: "Bestie Bundle",
    subtitle: "Two favourites, one special price",
    description: "Choose selected fragrances or accessories for you and your favourite person.",
    priceLabel: "Message us for available combinations",
    imageUrl: null,
    productIds: ["vanilla-cloud", "classic-hoops"],
    startsAt: null,
    endsAt: null,
    publicationStatus: "published",
    sortOrder: 3,
  },
];
